### ISSUE TITLE
question for Svelte book

### ISSUE THREAD

**Issue by mvolkmann** [bestguy/sveltestrap#126]
@bestguy I opened an issue because I couldn't find another way to contact you. I'm writing the Manning book "Svelte and Sapper in Action". It contains a short section on integration with CSS libraries like Bootstrap. I'm planning to mention your sveltestrap library and include an example of using it.

Would you say it is not possible to use Bootstrap components in a Svelte app or just difficult. If I understand correctly, you reimplemented nearly all of the Bootstrap components as Svelte components which is great! Did you feel that was the only way to make them available in Svelte apps?

**Comment by bestguy** [comment]
Hi @mvolkmann  Oh nice!   Thank you for reaching out.   Mentioning is fine by me and appreciated.

> "Would you say it is not possible to use Bootstrap components in a Svelte app or just difficult"

I think that phrasing isn't correct; the purpose of Sveltestrap is to make using Bootstrap easier and offer a more Svelte-friendly interface as components.  More specifically this specifically means:

1. You need less markup/"div-soup" with the various combinations of bootstrap class names.  For example Carousels:

HTML:
```html
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="..." class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
```

Sveltestrap:

```html
const items = ['src1...', 'src2...', 'src3...'];
let activeIndex = 0;

<Carousel {items} bind:activeIndex>
  <div class="carousel-inner">
    {#each items as item}
      <CarouselItem bind:activeIndex itemIndex={index}>
        <img src={item} class="d-block w-100" />
      </CarouselItem>
    {/each}
  </div>

  <CarouselControl direction="prev" bind:activeIndex {items} />
  <CarouselControl direction="next" bind:activeIndex {items} />
</Carousel>
```

IMO Svelte components are a lot clearer vs parsing the lower level HTML.

2. Related to above, Bootstrap offers it's own JavaScript needed to use many of its interactive components, e.g.:
```javascript
$('.carousel').carousel();
```

While fine, the drawbacks are Bootstrap currently depends on jQuery, and does not 'play well' with dynamic UI frameworks like React, Svelte, etc.  To integrate the DOM-based JavaScript API is a little awkward.
Also, the JavaScript is a complete library and hard to selectively include or use when you are only using a few components.

Sveltestrap takes a different approach and does not depend on Bootstrap's JS. It instead implements equivalent behavior with Vanilla JS and/or Svelte plugins.  This allows for more selective includes of JS, smaller bundles, and generally a more "Svelte-native" experience so that you don't need to separately initialize components.


Some of this is certainly subjective, but being a UI developer, I find the component-centric libraries like Sveltestrap much easier to develop and maintain.  I started Sveltestrap since I didn't see good alternatives at the time, and grew tired of the div-soup when using Bootstrap.


Does this help clarify?

**Comment by bestguy** [comment]
@mvolkmann the TL;DR is using Bootstrap's class name HTML+JS based components directly are awkward compared to using reusable components designed for Svelte.  They use the same CSS under the hood so you get the benefits of Bootstrap without most of the drawbacks.

**Comment by mvolkmann** [comment]
Thanks, makes sense! When the book comes out you’ll see an example of using your library in the “Advanced Svelte” chapter.
