### ISSUE TITLE
ButtonGroup doesn't add "btn-group" to ButtonDropdown

### ISSUE THREAD

**Issue by vfilatov** [bestguy/sveltestrap#137]
https://svelte.dev/repl/103a4efed9a34756af12895bcd9e03f8?version=3.20.1

**Comment by kevsnams** [comment]
I was having the same problem too. I thought that by adding `<ButtonDropdown group=true>` it will fix the problem.

I went on and investigated a little more. It turns out on src/Dropdown.svelte, this line:

![image](https://user-images.githubusercontent.com/62271083/76898710-2f587000-68d1-11ea-9f19-0bda4dbde559.png)

`{...props}` also has class in it (from parent ButtonDropdown), and it overrides `class={classes}`. I think the solution will be either: remove the `{...props}` (I see no use of it anyway, I think???) OR apply `{...props}` to the element before setting its `class` attribute (this one is much easier).

**Comment by bestguy** [comment]
Sorry for the long delay, this was corrected in [v4.0.0](https://github.com/bestguy/sveltestrap/releases/tag/v4.0.0).
The real looks to work correctly now: https://svelte.dev/repl/103a4efed9a34756af12895bcd9e03f8?version=3.20.1
