### ISSUE TITLE
modal static

### ISSUE THREAD

**Issue by junaidy-johm** [bestguy/sveltestrap#234]
How to make modal static mode

**Comment by bestguy** [comment]
Hi @junaidy-johm , looks like a bug!  We are unable to pass the correct styles and disable backdrop without some code changes.  We'll correct this week, thanks for the heads up.

**Comment by abbychau** [comment]
is it fixed?

**Comment by bestguy** [comment]
Hi, not yet, sorry I saw a few other issues with Modal and a delay fixing them.  I'll try and address this week.

**Comment by bestguy** [comment]
Hi @junaidy-johm @abbychau ,

We've published `sveltestrap@4.0.0-alpha.1` that supports this if you could please install (`npm install sveltestrap@4.0.0-alpha.1`) and confirm it works for you. 

Note we had to bump to v4 since another modal fix requires a newer version of svelte to support.

Please reply here and/or close and we can publish an official v4 release.

**Comment by bestguy** [comment]
Hi this is released in `sveltestrap@3.14.0`
Please see docs here under "Static": https://sveltestrap.js.org/?path=/story/components--modals

Please reopen if you see any issues.
