### ISSUE TITLE
Best-Practice for default component styling

### ISSUE THREAD

**Issue by Conceptiks** [bestguy/sveltestrap#336]
I have recently started using svelte and as a long-time bootstrap user, I love using sveltestrap. However, I was wondering if there is a best practice for styling default sveltestrap components. Let's take a bit a sample code (from the documentation) as an example:

Supposed I have a card like this:
`<Card>
  <CardBody>Hello World</CardBody>
</Card>`

Is it possible to access this `<Card></Card>` component in order to style it? I have tried to access it like so:

`<style>
.card {
  background: red;
}
</style>`

Predictably, this fails as the compiler is too smart as to include "unused" styles. Is there a standard way of accessing default component styles? Must I assign a class to each component? To me, this solution seems odd as it sort of defeats the purpose of component-level-styles?

**Comment by bestguy** [comment]
Hi @Conceptiks , it depends on what you would like to accomplish.  
If you need to do a quick override for a component or two, you can do this:

```css
<style>
  :global(.card) {
    background: red; 
  } 
</style>
```
The `:global(...)` is required by svelte otherwise it's scoped with some generated class name. You can read more here:
https://svelte.dev/docs#style


But if you want to change your entire app's theme to match company branding, etc this is not the way to go.  You should instead look into making/using a custom Bootstrap theme so that lots of styles/overrides aren't built into your JavaScript code.

Hope this helps.

**Comment by bestguy** [comment]
Closing, please comment if not resolved for you.
